// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTu4sbaTeEi4g9KBZJghbYeIkAD23-8fk',
    appId: '1:533641156076:web:db80ee6221aa6e1a45dcc9',
    messagingSenderId: '533641156076',
    projectId: 'park-lion',
    authDomain: 'park-lion.firebaseapp.com',
    storageBucket: 'park-lion.firebasestorage.app',
    measurementId: 'G-Q9L3F73S7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6g88oZpcrdcl0tXB-3j_MQUJecnC1SIU',
    appId: '1:533641156076:android:ae6ef7221164378045dcc9',
    messagingSenderId: '533641156076',
    projectId: 'park-lion',
    storageBucket: 'park-lion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTXI9h0mSCUv4TmPnHUjJ7PN9ZvGV4qGQ',
    appId: '1:533641156076:ios:c10e0b2d37b1475e45dcc9',
    messagingSenderId: '533641156076',
    projectId: 'park-lion',
    storageBucket: 'park-lion.firebasestorage.app',
    iosBundleId: 'com.example.parkLion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTXI9h0mSCUv4TmPnHUjJ7PN9ZvGV4qGQ',
    appId: '1:533641156076:ios:c10e0b2d37b1475e45dcc9',
    messagingSenderId: '533641156076',
    projectId: 'park-lion',
    storageBucket: 'park-lion.firebasestorage.app',
    iosBundleId: 'com.example.parkLion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTu4sbaTeEi4g9KBZJghbYeIkAD23-8fk',
    appId: '1:533641156076:web:d759c6b57a588a8d45dcc9',
    messagingSenderId: '533641156076',
    projectId: 'park-lion',
    authDomain: 'park-lion.firebaseapp.com',
    storageBucket: 'park-lion.firebasestorage.app',
    measurementId: 'G-BXTK52NSHW',
  );
}
